language: node_js
node_js:
  - 8.9
  - 9
script:
  - make ci
sudo: false
if: tag IS blank
before_install: git fetch --unshallow
after_success:
  - travis-spawn-once .travis/after_success.sh --skipPR --ghTokenName=RELEASE_GH_TOKEN
