// flow-typed signature: 2d77b1dc149617e91cdfb01ccac89d7e
// flow-typed version: <<STUB>>/@commitlint/config-lerna-scopes_v^4.2.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@commitlint/config-lerna-scopes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@commitlint/config-lerna-scopes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@commitlint/config-lerna-scopes/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@commitlint/config-lerna-scopes/index' {
  declare module.exports: $Exports<'@commitlint/config-lerna-scopes'>;
}
declare module '@commitlint/config-lerna-scopes/index.js' {
  declare module.exports: $Exports<'@commitlint/config-lerna-scopes'>;
}
declare module '@commitlint/config-lerna-scopes/test.js' {
  declare module.exports: $Exports<'@commitlint/config-lerna-scopes/test'>;
}
