// flow-typed signature: 736a462ebc3f8f40d310fc019e85ff3e
// flow-typed version: <<STUB>>/chalk_v2.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chalk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chalk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'chalk/index' {
  declare module.exports: $Exports<'chalk'>;
}
declare module 'chalk/index.js' {
  declare module.exports: $Exports<'chalk'>;
}
