// flow-typed signature: f855c2921d9d6c8e6e82590afb7d865b
// flow-typed version: <<STUB>>/commitlint_v^4.2.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'commitlint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'commitlint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'commitlint/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'commitlint/cli.js' {
  declare module.exports: $Exports<'commitlint/cli'>;
}
