// flow-typed signature: 034cb1f7d25bbf6c13fa771fac7c332f
// flow-typed version: <<STUB>>/documentation_v4.0.0-rc.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'documentation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'documentation' {
  declare module.exports: any;
}
