// flow-typed signature: 08204eaa9e978f99903ae7d26400eef1
// flow-typed version: <<STUB>>/html-minifier_v^3.5.8/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-minifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-minifier' {
  declare module.exports: any;
}
