// flow-typed signature: a6a191a5b584d8953e15894ad2ef015c
// flow-typed version: <<STUB>>/jest-flow-transform_v1.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-flow-transform'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-flow-transform' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-flow-transform/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-flow-transform/index' {
  declare module.exports: $Exports<'jest-flow-transform'>;
}
declare module 'jest-flow-transform/index.js' {
  declare module.exports: $Exports<'jest-flow-transform'>;
}
declare module 'jest-flow-transform/index.test.js' {
  declare module.exports: $Exports<'jest-flow-transform/index.test'>;
}
