// flow-typed signature: 1ecca419e22f7c2ab5c86f9c20550807
// flow-typed version: <<STUB>>/markdown-toc_v1.2.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-toc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-toc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown-toc/cli' {
  declare module.exports: any;
}

declare module 'markdown-toc/lib/insert' {
  declare module.exports: any;
}

declare module 'markdown-toc/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown-toc/cli.js' {
  declare module.exports: $Exports<'markdown-toc/cli'>;
}
declare module 'markdown-toc/index' {
  declare module.exports: $Exports<'markdown-toc'>;
}
declare module 'markdown-toc/index.js' {
  declare module.exports: $Exports<'markdown-toc'>;
}
declare module 'markdown-toc/lib/insert.js' {
  declare module.exports: $Exports<'markdown-toc/lib/insert'>;
}
declare module 'markdown-toc/lib/utils.js' {
  declare module.exports: $Exports<'markdown-toc/lib/utils'>;
}
