// flow-typed signature: 22b698525820b417d06c3a60d7af3e94
// flow-typed version: <<STUB>>/marked_v0.3.7/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'marked'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'marked' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'marked/Gulpfile' {
  declare module.exports: any;
}

declare module 'marked/lib/marked' {
  declare module.exports: any;
}

declare module 'marked/marked.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'marked/Gulpfile.js' {
  declare module.exports: $Exports<'marked/Gulpfile'>;
}
declare module 'marked/index' {
  declare module.exports: $Exports<'marked'>;
}
declare module 'marked/index.js' {
  declare module.exports: $Exports<'marked'>;
}
declare module 'marked/lib/marked.js' {
  declare module.exports: $Exports<'marked/lib/marked'>;
}
declare module 'marked/marked.min.js' {
  declare module.exports: $Exports<'marked/marked.min'>;
}
