// flow-typed signature: 04f83e465e353d63ae079fa70033c916
// flow-typed version: <<STUB>>/node-emoji_v1.5.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-emoji'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-emoji' {
  declare module.exports: any;
}
