// flow-typed signature: eef5fb09540b5a99aa456f20487d5faa
// flow-typed version: <<STUB>>/rehype-stringify_v3.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rehype-stringify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rehype-stringify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'rehype-stringify/index' {
  declare module.exports: $Exports<'rehype-stringify'>;
}
declare module 'rehype-stringify/index.js' {
  declare module.exports: $Exports<'rehype-stringify'>;
}
