// flow-typed signature: b1ef91e40c856f053f1182848ecc4008
// flow-typed version: <<STUB>>/rehype-preset-minify_v^2.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rehype-preset-minify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rehype-preset-minify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'rehype-preset-minify/index' {
  declare module.exports: $Exports<'rehype-preset-minify'>;
}
declare module 'rehype-preset-minify/index.js' {
  declare module.exports: $Exports<'rehype-preset-minify'>;
}
