// flow-typed signature: 16c93b7e0eeb9fb6c9eb42757f297a8b
// flow-typed version: <<STUB>>/remark-rehype_v2.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-rehype'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-rehype' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'remark-rehype/index' {
  declare module.exports: $Exports<'remark-rehype'>;
}
declare module 'remark-rehype/index.js' {
  declare module.exports: $Exports<'remark-rehype'>;
}
