// flow-typed signature: 41a5627f410ecfd0fd5bec3dc109d5fc
// flow-typed version: <<STUB>>/smartypants_v0.0.5/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'smartypants'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'smartypants' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'smartypants/bin/smartypants' {
  declare module.exports: any;
}

declare module 'smartypants/bin/smartypantsu' {
  declare module.exports: any;
}

declare module 'smartypants/smartypants.es6' {
  declare module.exports: any;
}

declare module 'smartypants/smartypants' {
  declare module.exports: any;
}

// Filename aliases
declare module 'smartypants/bin/smartypants.js' {
  declare module.exports: $Exports<'smartypants/bin/smartypants'>;
}
declare module 'smartypants/bin/smartypantsu.js' {
  declare module.exports: $Exports<'smartypants/bin/smartypantsu'>;
}
declare module 'smartypants/smartypants.es6.js' {
  declare module.exports: $Exports<'smartypants/smartypants.es6'>;
}
declare module 'smartypants/smartypants.js' {
  declare module.exports: $Exports<'smartypants/smartypants'>;
}
