// flow-typed signature: a1ea5f22481cb134d6ee0f5ddba52eff
// flow-typed version: <<STUB>>/unified_v6.1.5/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unified'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unified' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'unified/index' {
  declare module.exports: $Exports<'unified'>;
}
declare module 'unified/index.js' {
  declare module.exports: $Exports<'unified'>;
}
