const shields = require('./');

describe('@emdaer/plugin-shields', () => {
  test('generates shields', async () => {
    expect(
      await shields({
        shields: [
          {
            alt: 'This file was generated by emdaer',
            image: 'badge/📓-emdaer-F06632.svg',
            link: 'https://emdaer.netlify.com/',
            style: 'flat-square',
          },
          {
            alt: 'Travis',
            image: 'travis/emdaer/emdaer.svg',
            link: 'https://travis-ci.org/emdaer/emdaer/',
            style: 'flat-square',
          },
        ],
      })
    ).toBe(
      `[![This file was generated by emdaer](https://img.shields.io/badge/📓-emdaer-F06632.svg?style=flat-square)](https://emdaer.netlify.com/) [![Travis](https://img.shields.io/travis/emdaer/emdaer.svg?style=flat-square)](https://travis-ci.org/emdaer/emdaer/)`
    );
  });
  test('has defaults', async () => {
    expect(
      await shields({
        shields: [{}],
      })
    ).toBe(`[![](https://img.shields.io/?style=plastic)]()`);
  });
});
