// flow-typed signature: f55af3d89992eac879e64ad85fd4dfd1
// flow-typed version: <<STUB>>/@emdaer/cli_vfile:packages/cli/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emdaer/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emdaer/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emdaer/cli/lib/_errors' {
  declare module.exports: any;
}

declare module '@emdaer/cli/lib/_logger' {
  declare module.exports: any;
}

declare module '@emdaer/cli/lib/index' {
  declare module.exports: any;
}

declare module '@emdaer/cli/src/_errors' {
  declare module.exports: any;
}

declare module '@emdaer/cli/src/_logger' {
  declare module.exports: any;
}

declare module '@emdaer/cli/src/_logger.test' {
  declare module.exports: any;
}

declare module '@emdaer/cli/src/index' {
  declare module.exports: any;
}

declare module '@emdaer/cli/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emdaer/cli/lib/_errors.js' {
  declare module.exports: $Exports<'@emdaer/cli/lib/_errors'>;
}
declare module '@emdaer/cli/lib/_logger.js' {
  declare module.exports: $Exports<'@emdaer/cli/lib/_logger'>;
}
declare module '@emdaer/cli/lib/index.js' {
  declare module.exports: $Exports<'@emdaer/cli/lib/index'>;
}
declare module '@emdaer/cli/src/_errors.js' {
  declare module.exports: $Exports<'@emdaer/cli/src/_errors'>;
}
declare module '@emdaer/cli/src/_logger.js' {
  declare module.exports: $Exports<'@emdaer/cli/src/_logger'>;
}
declare module '@emdaer/cli/src/_logger.test.js' {
  declare module.exports: $Exports<'@emdaer/cli/src/_logger.test'>;
}
declare module '@emdaer/cli/src/index.js' {
  declare module.exports: $Exports<'@emdaer/cli/src/index'>;
}
declare module '@emdaer/cli/src/index.test.js' {
  declare module.exports: $Exports<'@emdaer/cli/src/index.test'>;
}
