// flow-typed signature: 7bd1873a48afafbd8c8256389c872120
// flow-typed version: <<STUB>>/@emdaer/core_vfile:packages/core/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emdaer/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emdaer/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emdaer/core/lib/errors' {
  declare module.exports: any;
}

declare module '@emdaer/core/lib/types' {
  declare module.exports: any;
}

declare module '@emdaer/core/lib/index' {
  declare module.exports: any;
}

declare module '@emdaer/core/lib/util/addStamp' {
  declare module.exports: any;
}

declare module '@emdaer/core/lib/util/applyTransform' {
  declare module.exports: any;
}

declare module '@emdaer/core/lib/util/applyTransforms' {
  declare module.exports: any;
}

declare module '@emdaer/core/lib/util/EmdaerError' {
  declare module.exports: any;
}

declare module '@emdaer/core/lib/util/executePlugin' {
  declare module.exports: any;
}

declare module '@emdaer/core/lib/util/executePlugins' {
  declare module.exports: any;
}

declare module '@emdaer/core/lib/util/identifyTransforms' {
  declare module.exports: any;
}

declare module '@emdaer/core/lib/util/resolvePlugin' {
  declare module.exports: any;
}

declare module '@emdaer/core/lib/util/resolveTransform' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/errors' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/types' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/index' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/index.test' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/addStamp' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/addStamp.test' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/applyTransform' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/applyTransform.test' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/applyTransforms' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/applyTransforms.test' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/EmdaerError' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/EmdaerError.test' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/executePlugin' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/executePlugin.test' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/executePlugins' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/executePlugins.test' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/identifyTransforms' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/identifyTransforms.test' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/resolvePlugin' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/resolvePlugin.test' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/resolveTransform' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/util/resolveTransform.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emdaer/core/lib/errors.js' {
  declare module.exports: $Exports<'@emdaer/core/lib/errors'>;
}
declare module '@emdaer/core/lib/types.js' {
  declare module.exports: $Exports<'@emdaer/core/lib/types'>;
}
declare module '@emdaer/core/lib/index.js' {
  declare module.exports: $Exports<'@emdaer/core/lib/index'>;
}
declare module '@emdaer/core/lib/util/addStamp.js' {
  declare module.exports: $Exports<'@emdaer/core/lib/util/addStamp'>;
}
declare module '@emdaer/core/lib/util/applyTransform.js' {
  declare module.exports: $Exports<'@emdaer/core/lib/util/applyTransform'>;
}
declare module '@emdaer/core/lib/util/applyTransforms.js' {
  declare module.exports: $Exports<'@emdaer/core/lib/util/applyTransforms'>;
}
declare module '@emdaer/core/lib/util/EmdaerError.js' {
  declare module.exports: $Exports<'@emdaer/core/lib/util/EmdaerError'>;
}
declare module '@emdaer/core/lib/util/executePlugin.js' {
  declare module.exports: $Exports<'@emdaer/core/lib/util/executePlugin'>;
}
declare module '@emdaer/core/lib/util/executePlugins.js' {
  declare module.exports: $Exports<'@emdaer/core/lib/util/executePlugins'>;
}
declare module '@emdaer/core/lib/util/identifyTransforms.js' {
  declare module.exports: $Exports<'@emdaer/core/lib/util/identifyTransforms'>;
}
declare module '@emdaer/core/lib/util/resolvePlugin.js' {
  declare module.exports: $Exports<'@emdaer/core/lib/util/resolvePlugin'>;
}
declare module '@emdaer/core/lib/util/resolveTransform.js' {
  declare module.exports: $Exports<'@emdaer/core/lib/util/resolveTransform'>;
}
declare module '@emdaer/core/src/errors.js' {
  declare module.exports: $Exports<'@emdaer/core/src/errors'>;
}
declare module '@emdaer/core/src/types.js' {
  declare module.exports: $Exports<'@emdaer/core/src/types'>;
}
declare module '@emdaer/core/src/index.js' {
  declare module.exports: $Exports<'@emdaer/core/src/index'>;
}
declare module '@emdaer/core/src/index.test.js' {
  declare module.exports: $Exports<'@emdaer/core/src/index.test'>;
}
declare module '@emdaer/core/src/util/addStamp.js' {
  declare module.exports: $Exports<'@emdaer/core/src/util/addStamp'>;
}
declare module '@emdaer/core/src/util/addStamp.test.js' {
  declare module.exports: $Exports<'@emdaer/core/src/util/addStamp.test'>;
}
declare module '@emdaer/core/src/util/applyTransform.js' {
  declare module.exports: $Exports<'@emdaer/core/src/util/applyTransform'>;
}
declare module '@emdaer/core/src/util/applyTransform.test.js' {
  declare module.exports: $Exports<'@emdaer/core/src/util/applyTransform.test'>;
}
declare module '@emdaer/core/src/util/applyTransforms.js' {
  declare module.exports: $Exports<'@emdaer/core/src/util/applyTransforms'>;
}
declare module '@emdaer/core/src/util/applyTransforms.test.js' {
  declare module.exports: $Exports<
    '@emdaer/core/src/util/applyTransforms.test'
  >;
}
declare module '@emdaer/core/src/util/EmdaerError.js' {
  declare module.exports: $Exports<'@emdaer/core/src/util/EmdaerError'>;
}
declare module '@emdaer/core/src/util/EmdaerError.test.js' {
  declare module.exports: $Exports<'@emdaer/core/src/util/EmdaerError.test'>;
}
declare module '@emdaer/core/src/util/executePlugin.js' {
  declare module.exports: $Exports<'@emdaer/core/src/util/executePlugin'>;
}
declare module '@emdaer/core/src/util/executePlugin.test.js' {
  declare module.exports: $Exports<'@emdaer/core/src/util/executePlugin.test'>;
}
declare module '@emdaer/core/src/util/executePlugins.js' {
  declare module.exports: $Exports<'@emdaer/core/src/util/executePlugins'>;
}
declare module '@emdaer/core/src/util/executePlugins.test.js' {
  declare module.exports: $Exports<'@emdaer/core/src/util/executePlugins.test'>;
}
declare module '@emdaer/core/src/util/identifyTransforms.js' {
  declare module.exports: $Exports<'@emdaer/core/src/util/identifyTransforms'>;
}
declare module '@emdaer/core/src/util/identifyTransforms.test.js' {
  declare module.exports: $Exports<
    '@emdaer/core/src/util/identifyTransforms.test'
  >;
}
declare module '@emdaer/core/src/util/resolvePlugin.js' {
  declare module.exports: $Exports<'@emdaer/core/src/util/resolvePlugin'>;
}
declare module '@emdaer/core/src/util/resolvePlugin.test.js' {
  declare module.exports: $Exports<'@emdaer/core/src/util/resolvePlugin.test'>;
}
declare module '@emdaer/core/src/util/resolveTransform.js' {
  declare module.exports: $Exports<'@emdaer/core/src/util/resolveTransform'>;
}
declare module '@emdaer/core/src/util/resolveTransform.test.js' {
  declare module.exports: $Exports<
    '@emdaer/core/src/util/resolveTransform.test'
  >;
}
