// flow-typed signature: 4404ebac06d42252d1b6c8c63a42398b
// flow-typed version: <<STUB>>/@emdaer/core_v^1.0.0-alpha.7/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emdaer/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emdaer/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emdaer/core/__tests__/index' {
  declare module.exports: any;
}

declare module '@emdaer/core/lib/_errors' {
  declare module.exports: any;
}

declare module '@emdaer/core/lib/_types' {
  declare module.exports: any;
}

declare module '@emdaer/core/lib/index' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/_errors' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/_types' {
  declare module.exports: any;
}

declare module '@emdaer/core/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emdaer/core/__tests__/index.js' {
  declare module.exports: $Exports<'@emdaer/core/__tests__/index'>;
}
declare module '@emdaer/core/lib/_errors.js' {
  declare module.exports: $Exports<'@emdaer/core/lib/_errors'>;
}
declare module '@emdaer/core/lib/_types.js' {
  declare module.exports: $Exports<'@emdaer/core/lib/_types'>;
}
declare module '@emdaer/core/lib/index.js' {
  declare module.exports: $Exports<'@emdaer/core/lib/index'>;
}
declare module '@emdaer/core/src/_errors.js' {
  declare module.exports: $Exports<'@emdaer/core/src/_errors'>;
}
declare module '@emdaer/core/src/_types.js' {
  declare module.exports: $Exports<'@emdaer/core/src/_types'>;
}
declare module '@emdaer/core/src/index.js' {
  declare module.exports: $Exports<'@emdaer/core/src/index'>;
}
