// flow-typed signature: fa3453f9c5d5008b3e9de714a5ac931a
// flow-typed version: <<STUB>>/@emdaer/plugin-shields_vfile:packages/plugin-shields/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emdaer/plugin-shields'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emdaer/plugin-shields' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emdaer/plugin-shields/lib/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-shields/src/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-shields/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emdaer/plugin-shields/lib/index.js' {
  declare module.exports: $Exports<'@emdaer/plugin-shields/lib/index'>;
}
declare module '@emdaer/plugin-shields/src/index.js' {
  declare module.exports: $Exports<'@emdaer/plugin-shields/src/index'>;
}
declare module '@emdaer/plugin-shields/src/index.test.js' {
  declare module.exports: $Exports<'@emdaer/plugin-shields/src/index.test'>;
}
