// flow-typed signature: 8407495437004e7481bb0136491f96af
// flow-typed version: <<STUB>>/@emdaer/plugin-license-reference_vfile:packages/plugin-license-reference/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emdaer/plugin-license-reference'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emdaer/plugin-license-reference' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emdaer/plugin-license-reference/lib/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-license-reference/src/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-license-reference/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emdaer/plugin-license-reference/lib/index.js' {
  declare module.exports: $Exports<
    '@emdaer/plugin-license-reference/lib/index'
  >;
}
declare module '@emdaer/plugin-license-reference/src/index.js' {
  declare module.exports: $Exports<
    '@emdaer/plugin-license-reference/src/index'
  >;
}
declare module '@emdaer/plugin-license-reference/src/index.test.js' {
  declare module.exports: $Exports<
    '@emdaer/plugin-license-reference/src/index.test'
  >;
}
