// flow-typed signature: 0ba99159e7480a4a5b97e94b5af3fa94
// flow-typed version: <<STUB>>/@emdaer/plugin-code-block_v^1.0.0-alpha.7/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emdaer/plugin-code-block'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emdaer/plugin-code-block' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emdaer/plugin-code-block/__tests__/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-code-block/lib/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-code-block/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emdaer/plugin-code-block/__tests__/index.js' {
  declare module.exports: $Exports<'@emdaer/plugin-code-block/__tests__/index'>;
}
declare module '@emdaer/plugin-code-block/lib/index.js' {
  declare module.exports: $Exports<'@emdaer/plugin-code-block/lib/index'>;
}
declare module '@emdaer/plugin-code-block/src/index.js' {
  declare module.exports: $Exports<'@emdaer/plugin-code-block/src/index'>;
}
