// flow-typed signature: ac488073e358fac3d12a79cf5efa3092
// flow-typed version: <<STUB>>/@emdaer/plugin-documentation_vfile:packages/plugin-documentation/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emdaer/plugin-documentation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emdaer/plugin-documentation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emdaer/plugin-documentation/lib/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-documentation/src/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-documentation/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emdaer/plugin-documentation/lib/index.js' {
  declare module.exports: $Exports<'@emdaer/plugin-documentation/lib/index'>;
}
declare module '@emdaer/plugin-documentation/src/index.js' {
  declare module.exports: $Exports<'@emdaer/plugin-documentation/src/index'>;
}
declare module '@emdaer/plugin-documentation/src/index.test.js' {
  declare module.exports: $Exports<
    '@emdaer/plugin-documentation/src/index.test'
  >;
}
