// flow-typed signature: cc6220488129acb0f45a6d4c4b9b4f74
// flow-typed version: <<STUB>>/@emdaer/plugin-list-lerna-packages_vfile:packages/plugin-list-lerna-packages/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emdaer/plugin-list-lerna-packages'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emdaer/plugin-list-lerna-packages' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emdaer/plugin-list-lerna-packages/lib/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-list-lerna-packages/src/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-list-lerna-packages/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emdaer/plugin-list-lerna-packages/lib/index.js' {
  declare module.exports: $Exports<
    '@emdaer/plugin-list-lerna-packages/lib/index'
  >;
}
declare module '@emdaer/plugin-list-lerna-packages/src/index.js' {
  declare module.exports: $Exports<
    '@emdaer/plugin-list-lerna-packages/src/index'
  >;
}
declare module '@emdaer/plugin-list-lerna-packages/src/index.test.js' {
  declare module.exports: $Exports<
    '@emdaer/plugin-list-lerna-packages/src/index.test'
  >;
}
