// flow-typed signature: 3caabbf4c4e15f965fb9b5fb7cb39f99
// flow-typed version: <<STUB>>/@emdaer/plugin-contributors-details-github_vfile:packages/plugin-contributors-details-github/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emdaer/plugin-contributors-details-github'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emdaer/plugin-contributors-details-github' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emdaer/plugin-contributors-details-github/lib/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-contributors-details-github/scripts/postinstall' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-contributors-details-github/scripts/preuninstall' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-contributors-details-github/src/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-contributors-details-github/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emdaer/plugin-contributors-details-github/lib/index.js' {
  declare module.exports: $Exports<
    '@emdaer/plugin-contributors-details-github/lib/index'
  >;
}
declare module '@emdaer/plugin-contributors-details-github/scripts/postinstall.js' {
  declare module.exports: $Exports<
    '@emdaer/plugin-contributors-details-github/scripts/postinstall'
  >;
}
declare module '@emdaer/plugin-contributors-details-github/scripts/preuninstall.js' {
  declare module.exports: $Exports<
    '@emdaer/plugin-contributors-details-github/scripts/preuninstall'
  >;
}
declare module '@emdaer/plugin-contributors-details-github/src/index.js' {
  declare module.exports: $Exports<
    '@emdaer/plugin-contributors-details-github/src/index'
  >;
}
declare module '@emdaer/plugin-contributors-details-github/src/index.test.js' {
  declare module.exports: $Exports<
    '@emdaer/plugin-contributors-details-github/src/index.test'
  >;
}
