// flow-typed signature: d5504d38ed3c6e1584166e4eba704f5b
// flow-typed version: <<STUB>>/@emdaer/plugin-import_vfile:packages/plugin-import/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emdaer/plugin-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emdaer/plugin-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emdaer/plugin-import/lib/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-import/src/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-import/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emdaer/plugin-import/lib/index.js' {
  declare module.exports: $Exports<'@emdaer/plugin-import/lib/index'>;
}
declare module '@emdaer/plugin-import/src/index.js' {
  declare module.exports: $Exports<'@emdaer/plugin-import/src/index'>;
}
declare module '@emdaer/plugin-import/src/index.test.js' {
  declare module.exports: $Exports<'@emdaer/plugin-import/src/index.test'>;
}
