// flow-typed signature: 96ae4076f7bb00559f78a39748580624
// flow-typed version: <<STUB>>/@emdaer/plugin-linebreak_v^1.0.0-alpha.12/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emdaer/plugin-linebreak'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emdaer/plugin-linebreak' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emdaer/plugin-linebreak/__tests__/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-linebreak/lib/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-linebreak/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emdaer/plugin-linebreak/__tests__/index.js' {
  declare module.exports: $Exports<'@emdaer/plugin-linebreak/__tests__/index'>;
}
declare module '@emdaer/plugin-linebreak/lib/index.js' {
  declare module.exports: $Exports<'@emdaer/plugin-linebreak/lib/index'>;
}
declare module '@emdaer/plugin-linebreak/src/index.js' {
  declare module.exports: $Exports<'@emdaer/plugin-linebreak/src/index'>;
}
