// flow-typed signature: 8c5dcf3500a0843051f5faa460b1c9f8
// flow-typed version: <<STUB>>/@emdaer/plugin-heading_v^1.0.0-alpha.7/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emdaer/plugin-heading'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emdaer/plugin-heading' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emdaer/plugin-heading/__tests__/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-heading/lib/index' {
  declare module.exports: any;
}

declare module '@emdaer/plugin-heading/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emdaer/plugin-heading/__tests__/index.js' {
  declare module.exports: $Exports<'@emdaer/plugin-heading/__tests__/index'>;
}
declare module '@emdaer/plugin-heading/lib/index.js' {
  declare module.exports: $Exports<'@emdaer/plugin-heading/lib/index'>;
}
declare module '@emdaer/plugin-heading/src/index.js' {
  declare module.exports: $Exports<'@emdaer/plugin-heading/src/index'>;
}
