// flow-typed signature: e810cf9104b68780e870a96dd5b3954a
// flow-typed version: <<STUB>>/@emdaer/transform-prettier_vfile:packages/transform-prettier/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emdaer/transform-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emdaer/transform-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emdaer/transform-prettier/lib/index' {
  declare module.exports: any;
}

declare module '@emdaer/transform-prettier/src/index' {
  declare module.exports: any;
}

declare module '@emdaer/transform-prettier/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emdaer/transform-prettier/lib/index.js' {
  declare module.exports: $Exports<'@emdaer/transform-prettier/lib/index'>;
}
declare module '@emdaer/transform-prettier/src/index.js' {
  declare module.exports: $Exports<'@emdaer/transform-prettier/src/index'>;
}
declare module '@emdaer/transform-prettier/src/index.test.js' {
  declare module.exports: $Exports<'@emdaer/transform-prettier/src/index.test'>;
}
