// flow-typed signature: 354db47149ae2c042305461056685707
// flow-typed version: <<STUB>>/@emdaer/transform-smartypants_v^1.0.0-alpha.14/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emdaer/transform-smartypants'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emdaer/transform-smartypants' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emdaer/transform-smartypants/__tests__/index' {
  declare module.exports: any;
}

declare module '@emdaer/transform-smartypants/lib/index' {
  declare module.exports: any;
}

declare module '@emdaer/transform-smartypants/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emdaer/transform-smartypants/__tests__/index.js' {
  declare module.exports: $Exports<
    '@emdaer/transform-smartypants/__tests__/index'
  >;
}
declare module '@emdaer/transform-smartypants/lib/index.js' {
  declare module.exports: $Exports<'@emdaer/transform-smartypants/lib/index'>;
}
declare module '@emdaer/transform-smartypants/src/index.js' {
  declare module.exports: $Exports<'@emdaer/transform-smartypants/src/index'>;
}
