/* @flow */

/*
Adds a stamp to the file
*/
module.exports = function addStamp(content: string, origin: string) {
  const relativeOrigin = origin.replace(`${process.cwd()}/`, '');
  return `<!--
  This file was generated by emdaer

  Its template can be found at ${relativeOrigin}
-->

${content}`;
};
