/* @flow */

/*
Adds a stamp to the file
*/
module.exports = function addStamp(content: string, origin: string) {
  return `<!--
  This file was generated by emdaer

  Its template can be found at ${origin}
-->

${content}`;
};
